### ISSUE TITLE
Empty elements being inserted in head

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/flexslider#9]
This is happening when I use Flexslider Fields and have a flexslider on a page. I had [posted as a core issue](https://github.com/backdrop/backdrop-issues/issues/3010) but it seems it may be a bug in the module.

A pair of empty elements are inserted into the `<head>` area of the code (and actually show up on the front end when viewing the site):
![screen shot 2018-03-29 at 10 23 16 am](https://user-images.githubusercontent.com/871421/38097639-83559b6a-333b-11e8-8051-f92efce58971.jpg)

The watchdog shows: 
`Notice: Undefined index: #tag in theme_head_tag() (line 2449 of /path/to/backdrop_html/core/includes/theme.inc).`

**Comment by jenlampton** [comment]
Looks like`#tag` should be part of the `element` instead.  
https://docs.backdropcms.org/api/backdrop/core%21includes%21theme.inc/function/theme_head_tag/1

Hmmm, there's no `head_tag` in the flexslider codebase. I'm not sure why flexslider would be adding a head tag. Have you been able to reproduce this since 2018? :D

**Comment by laryn** [comment]
> Have you been able to reproduce this since 2018? :D

Nope, and I just tried again (unsuccessfully) based on the first comment. Closing.
